apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  storageClassName: weblogic
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/wls-k8s-data/wls-k8s-mg"
