apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  storageClassName: weblogic
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /Users/mgianata/Downloads/weblogic-k8s-pv
